### ISSUE TITLE
Can't even load up the mod, even though I have all the requirements.

### ISSUE THREAD

**Issue by McWendigoes** [MoriyaShiine/aylyth#48]
### Mod version

fabric-loader-0.14.19-1.19.2

### A description of the issue

[latest.log](https://github.com/MoriyaShiine/aylyth/files/11309614/latest.log)

Seems to have trouble entering the entry point of the games launching sequence.

**Comment by dhyces** [comment]
Was there a crash or any more information given in the debug.log?

**Comment by McWendigoes** [comment]
Ah, sorry... wrong file. 
[crash-2023-04-24_11.44.25-client.txt](https://github.com/MoriyaShiine/aylyth/files/11327457/crash-2023-04-24_11.44.25-client.txt)
This should spell a picture.

**Comment by dhyces** [comment]
Next version will show a helpful error message for this. You need the Trinkets mod installed as well.
https://www.curseforge.com/minecraft/mc-mods/trinkets
https://modrinth.com/mod/trinkets/
