### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Ragabagayaga** [MoriyaShiine/aylyth#61]
### Mod version

2.0.1

### A description of the issue

On launch the game crashes
"The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'aylyth'!"
Exit Code:
-1

### Log or crash report

https://gist.github.com/Ragabagayaga/233fe2fb120eeb84a2b69d8ed5809d46

**Comment by dhyces** [comment]
Aylyth depends on the Trinkets mod

**Comment by Ragabagayaga** [comment]
> Aylyth depends on the Trinkets mod

Thanks for the help
